[project]
name = "andthe-python-linting-pipeline"
version = "1.0.0"
description = "Demo project for a medium article"
readme = "readme.md"
requires-python = ">=3.7"
authors = [
  {name = "Andreas Therkildsen"} # Optional
]
dependencies = [
    "sentry-sdk",
    "pytest",
    "ruff",
    "python-dotenv",
    "sqlfluff"
]

[build-system]
requires = ["setuptools>=65.5.0", "wheel"]
build-backend = "setuptools.build_meta"


[tool.ruff]

# Rules for ruff based on available standards and linters
[lint]
select = [
    "F",  # pyflakes (some undefined names)
    "E",  # pycodestyle
    "B",  # bugbear
    "UP", # pyupgrade
]

# Enable `N815` to enforce snake_case variable names
extend-select = [
  "N815", # Variable {name} in class scope should not be mixedCase
  "N816", # Variable {name} in global scope should not be mixedCase
  "N806", # Variable {name} in function should be lowercase
]

# Line length and indentions
line-length = 88
indent-width = 4
